language: java
os:
  - linux
jdk:
  - openjdk10
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
